# Generated by Django 5.2.9 on 2025-12-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_otplogin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="email_otp",
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures"
            ),
        ),
    ]
