# Generated by Django 5.2.9 on 2025-12-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_customuser_email_otp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(
                default="profile_pic/profile.png", upload_to="profile_pictures"
            ),
        ),
    ]
