# Generated by Django 5.2.9 on 2026-02-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_customuser_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="name",
        ),
        migrations.AddField(
            model_name="customuser",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="full_name"
            ),
        ),
    ]
