# Generated by Django 5.2.9 on 2026-04-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_ticket_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="replay",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ticket",
            name="replay_content",
            field=models.TextField(default=""),
        ),
    ]
