# Generated by Django 5.2.9 on 2026-04-26 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_ticket_replay_ticket_replay_content"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="replay",
            new_name="is_replied",
        ),
    ]
