# Generated by Django 5.2.9 on 2026-06-10 16:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_instructor_pendinglogin_instructorapplication"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="profile_picture",
        ),
    ]
