POST localhost:8000/api/auth/register/
Content-Type: application/json

{
  "identifier": "sghshrthdfhsdeds@gmail.com",
  "password1": "test123@a",
  "password2": "test123@a"
}

###

POST localhost:8000/api/auth/email-verify/
Authorization: Basic MTExOjExMQ==

###


POST localhost:8000/api/auth/code-verify/
Authorization: Basic MTExOjExMQ==
Content-Type: application/json

{
"code": "448686"
}

###

POST localhost:8000/api/auth/login/
Content-Type: application/json


{
  "username": "111",
  "password": "111"
}

###

POST localhost:8000/api/auth/logout/

Authorization: Basic MTExOjExMQ==

###
POST localhost:8000/api/auth/otp-login/
Content-Type: application/json

{
  "email": "mabo80800@gmail.com"
}
###
POST localhost:8000/api/auth/otp-login-verify/
Content-Type: application/json

{
  "email": "mabo80800@gmail.com",
  "code": "20501"
}

###
POST localhost:8000/api/auth/enable-two-factor-login/
Authorization: Basic MTExOjExMQ==


###


POST localhost:8000/api/auth/login/
Content-Type: application/json


{
  "username": "111",
  "password": "111"
}

###

POST localhost:8000/api/auth/verify-two-factor-login/
Content-Type: application/json

{
  "email": "mabo80800@gmail.com",
  "code": "dddd"
}

###
PATCH localhost:8000/api/auth/edit-profile/
Content-Type: application/json

{
  "first_name": "abolfazl",
  "last_name": "mirzaie"
}

###
POST localhost:8000/api/auth/password-reset-request/
Content-Type: application/json

{
  "email": "mabo80liut800@gmail.com"
}
###
POST http://127.0.0.1:8000/api/auth/reset-password/MQ/d1158d-9416c6baf704f89e6add0a858e1bd4d1/
Content-Type: application/json

{
  "new_password": 3080470436
}
###
POST localhost:8000/api/token/
Content-Type: application/json

{
  "username": "111",
  "password": "111"
}




###
GET localhost:8000/api/auth/plans/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY3Nzk1NjUyLCJpYXQiOjE3Njc3OTUzNTMsImp0aSI6IjY1MTY1NmRiN2EwNTQwZjBhOTViODcxNjZiMGRiMDJkIiwidXNlcl9pZCI6IjEifQ.8ppIhkz9kXHhcwJYuds9TUdo2xZUjwlnkaiNrpHHW-Q
###

GET localhost:8000/course-list/

###
POST http://localhost:8000/api/auth/tickets/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc3MjIzMTc5LCJpYXQiOjE3NzcyMjI4NzksImp0aSI6IjRkYWRmOTQ1MGY3MzRiZDI4OWRhN2JiODM0YTQ1MjU0IiwidXNlcl9pZCI6IjEifQ.Rm1eV3-rwvG2LEo9x9HCy-xZ6dlaweLPTI6M_GyoTz0
Content-Type: application/json

{
  "title" : "dfed",
  "description" : "sryesr"
}
###
GET localhost:8000/api/auth/tickets/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc3MjM0Nzk1LCJpYXQiOjE3NzcyMzQ0OTUsImp0aSI6ImM2ZWU2Njk4OWIzZTRjYmRiZGM1NWIzZWQxNGFjZGQ2IiwidXNlcl9pZCI6IjEifQ.e1Er-2Wnz2xSUa71LhBi3ur7HQ-APyaqyvuDFeyw11E
###

POST localhost:8000/courses/python/comments/create/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc3NTc3ODM3LCJpYXQiOjE3Nzc1Nzc1MzcsImp0aSI6IjE5NTViMjRkZTdiMDQ1MDZhNzY0MGJmNjVhZjg5ZmU1IiwidXNlcl9pZCI6IjEifQ.c0de4-Hi_1EUvEzrkxKum87Jn0DBVs3rthKhMGxl2VI
Content-Type: application/json

{
  "content" : "hello",
  "course" : "3"
}
###

POST localhost:8000/courses/python/enroll/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc4NDQ4ODg0LCJpYXQiOjE3Nzg0NDg1ODQsImp0aSI6IjYzMDZhNDlkMzM2YTQxNTI5ZGIwYjE4YjQ4MjYwODkwIiwidXNlcl9pZCI6IjEifQ.tkXw_QJt9zPjFsbeU15w7AX7vwyRdwVVNVxxf30nevg
###
GET localhost:8000/courses/python/students/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc3ODIxMjI5LCJpYXQiOjE3Nzc4MjA5MjksImp0aSI6Ijc3YThmZGJjNDRhODQ0MTZiYzYxMDRlMGNmZjk0ZGUyIiwidXNlcl9pZCI6IjEifQ.oGeXyLMFGICjGxjUmwVvsn1mkxI17acWwuB7H5ilpy0
###

GET localhost:8000/my/courses/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc4NDQ4ODg0LCJpYXQiOjE3Nzg0NDg1ODQsImp0aSI6IjYzMDZhNDlkMzM2YTQxNTI5ZGIwYjE4YjQ4MjYwODkwIiwidXNlcl9pZCI6IjEifQ.tkXw_QJt9zPjFsbeU15w7AX7vwyRdwVVNVxxf30nevg
