POST localhost:8000/api/auth/register/
Content-Type: application/json

{
  "identifier": "sghshrthdds@gmail.com",
  "password1": "test123@a",
  "password2": "test123@a"
}

###

POST localhost:8000/api/auth/email-verify/
Authorization: Basic MTExOjExMQ==

###


POST localhost:8000/api/auth/code-verify/
Authorization: Basic MTExOjExMQ==
Content-Type: application/json

{
"code": "448686"
}

###

POST localhost:8000/api/auth/login/
Content-Type: application/json


{
  "username": "111",
  "password": "111"
}

###

POST localhost:8000/api/auth/logout/

Authorization: Basic MTExOjExMQ==

###
POST localhost:8000/api/auth/otp-login/
Content-Type: application/json

{
  "email": "mabo80800@gmail.com"
}
###
POST localhost:8000/api/auth/otp-login-verify/
Content-Type: application/json

{
  "email": "mabo80800@gmail.com",
  "code": "20501"
}

###
POST localhost:8000/api/auth/enable-two-factor-login/
Authorization: Basic MTExOjExMQ==


###


POST localhost:8000/api/auth/login/
Content-Type: application/json


{
  "username": "111",
  "password": "111"
}

###

POST localhost:8000/api/auth/verify-two-factor-login/
Content-Type: application/json

{
  "email": "mabo80800@gmail.com",
  "code": "dddd"
}

###
PATCH localhost:8000/api/auth/edit-profile/
Content-Type: application/json

{
  "first_name": "abolfazl",
  "last_name": "mirzaie"
}

###
POST localhost:8000/api/auth/password-reset-request/
Content-Type: application/json

{
  "email": "mabo80liut800@gmail.com"
}
###
POST http://127.0.0.1:8000/api/auth/reset-password/MQ/d1158d-9416c6baf704f89e6add0a858e1bd4d1/
Content-Type: application/json

{
  "new_password": 3080470436
}
###
POST localhost:8000/api/token/
Content-Type: application/json

{
  "username": "111",
  "password": "111"
}




###
GET localhost:8000/api/auth/plans/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY3Nzk1NjUyLCJpYXQiOjE3Njc3OTUzNTMsImp0aSI6IjY1MTY1NmRiN2EwNTQwZjBhOTViODcxNjZiMGRiMDJkIiwidXNlcl9pZCI6IjEifQ.8ppIhkz9kXHhcwJYuds9TUdo2xZUjwlnkaiNrpHHW-Q
