# Generated by Django 5.2.9 on 2026-02-22 19:32

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_remove_course_is_premium_course_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_premium",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="title", unique=True
                    ),
                ),
                (
                    "course",
                    models.ManyToManyField(
                        related_name="categories", to="courses.course"
                    ),
                ),
            ],
        ),
    ]
