# Generated by Django 5.2.9 on 2026-02-23 17:38

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_course_is_premium_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default="slug-temp",
                editable=False,
                max_length=150,
                populate_from="title",
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
