# Generated by Django 5.2.9 on 2026-02-24 11:10
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_course_slug"),
    ]

    operations = [
        TrigramExtension(),
    ]
