# Generated by Django 5.2.9 on 2026-02-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_auto_20260224_1440"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={},
        ),
        migrations.AlterModelOptions(
            name="section",
            options={},
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="order",
        ),
        migrations.RemoveField(
            model_name="section",
            name="order",
        ),
        migrations.AddField(
            model_name="lesson",
            name="duration_second",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="lesson",
            name="video",
            field=models.FileField(blank=True, upload_to="lessons/video"),
        ),
        migrations.AlterField(
            model_name="course",
            name="image",
            field=models.ImageField(blank=True, upload_to="courses/image"),
        ),
    ]
