# Generated by Django 5.2.9 on 2026-02-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0006_alter_lesson_options_alter_section_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="duration_hour",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
