# Generated by Django 5.2.9 on 2026-02-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0007_lesson_duration_hour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video",
            field=models.FileField(blank=True, upload_to="courses/lessons/video"),
        ),
    ]
