# Generated by Django 5.2.9 on 2026-03-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0008_alter_lesson_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="level",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("medium", "Medium"),
                    ("advance", "Advance"),
                ],
                default="beginner",
                max_length=20,
            ),
        ),
    ]
