# Generated by Django 5.2.9 on 2026-03-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0009_alter_course_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=11)),
                ("address", models.CharField(max_length=120)),
            ],
        ),
    ]
