# Generated by Django 5.2.9 on 2026-04-23 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0011_ticket"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Ticket",
        ),
    ]
