# Generated by Django 5.2.9 on 2026-05-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0014_enrollment"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
