# Generated by Django 5.2.9 on 2026-06-08 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0017_courserating_lessonprogress_and_more"),
        ("users", "0016_instructor_pendinglogin_instructorapplication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="instructor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="users.instructor",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(),
        ),
    ]
