# Generated by Django 5.2.9 on 2026-06-10 16:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0018_alter_course_instructor_alter_lesson_video_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="courselike",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="courselike",
            constraint=models.UniqueConstraint(
                fields=("course", "user"), name="unique_course_like"
            ),
        ),
    ]
